CREATE TABLE IF NOT EXISTS CUSTOMER(
	CUS_ID NUMBER PRIMARY KEY,
	CUS_NAME VARCHAR(128)
);

CREATE TABLE IF NOT EXISTS ACCOUNT(
	ACT_ID NUMBER PRIMARY KEY,
	ACT_CUR_BLN NUMBER,
	ACT_CUS_ID NUMBER,
	FOREIGN KEY (ACT_CUS_ID) REFERENCES CUSTOMER(CUS_ID)
);

CREATE TABLE IF NOT EXISTS STATEMENTS(
	STM_ID NUMBER PRIMARY KEY,
	STM_TRAN_DATE TIMESTAMP,
	STM_TRAN_AMT NUMBER,
	STM_BLN NUMBER,
	STM_TRAN_TYPE VARCHAR(16),
	STM_ACT_ID NUMBER,
	FOREIGN KEY (STM_ACT_ID) REFERENCES ACCOUNT(ACT_ID)
);

CREATE SEQUENCE IF NOT EXISTS STATEMENTS_PK_SEQ START WITH 1 INCREMENT BY 1;

